### ISSUE TITLE
InvalidTokenException when intensive data exchange 

### ISSUE THREAD

**Issue by csfmeridian** [sgissinger/JabberNet-2010#2]
When one client exchange data with approximately 500 clients consistently observed this exception. I can not understand whether it is in the library is something wrong, or Openfire sends bad packets.
#### Recieved packet:

`<iq type="r52ult" id="JN_555" from="plg">b.srv-wp" to="kropadmin@srv-wp/XPMUser"/><iq id="JN_309" type="set" from="35215401@srv-wp/client" to="kropadmin@srv-wp/XPMUser"ame>clientupdate_334_4.pack</papp:updat`
#### Exception:

`jabber.protocol.AsynchElementStream+XMLParseException: Parsing exception ---> OFFSET: 168
TYPE: 0
xpnet.InvalidTokenException:  "xpnet.InvalidTokenException".
   в xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
   в xpnet.Encoding.scanLt(Byte[] buf, Int32 off, Int32 end, ContentToken token)
   в xpnet.Encoding.tokenizeContent(Byte[] buf, Int32 off, Int32 end, ContentToken token)
   в jabber.protocol.AsynchElementStream.Push(Byte[] buf, Int32 offset, Int32 length)
   в jabber.connection.SocketStanzaStream.bedrock.net.ISocketEventListener.OnRead(BaseSocket sock, Byte[] buf, Int32 offset, Int32 length)`
Context:
Outer element: `<iq from="plg" type="r52ult" id="JN_555">b.srv-wp" to="kropadmin@srv-wp/XPMUser"/&gt;</iq>
New text (note: it's normal to see what looks like extra close tags here): <iq type="r52ult" id="JN_555" from="plg">b.srv-wp" to="kropadmin@srv-wp/XPMUser"/><iq id="JN_309" type="set" from="35215401@srv-wp/client" to="kropadmin@srv-wp/XPMUser"ame>clientupdate_334_4.pack</papp:updat`
#### Сomments:

Where 
'r52ult' should be 'result',
'from="plg">b.srv-wp' should be 'from="pubsub.srv-wp'
'to="kropadmin@srv-wp/XPMUser"' should be 'to="kropadmin@srv-wp/User"',
also strange 'ame' and strfnge ending of packet '</papp:updat'

**Comment by sgissinger** [comment]
The exception is telling that the received IQ isn't a well-formed XML string.
And the section 'Recieved Packet' do not contains well-formed XML

This XMLParseException is thrown by .NET Framework not the library.

Based on that, I would think that OpenFire is sending bad IQs to your clients.

**Comment by csfmeridian** [comment]
Yep, error was in Apache Mina which using by Openfire.
